version: '3.8'

networks:
  ctf-network:
    driver: bridge

services:
  # Traefik 리버스 프록시
  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Traefik 대시보드
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ctf-network

  # CTFd 플랫폼 (볼륨 바인딩으로 데이터 보존)
  ctfd:
    image: ctfd/ctfd:latest
    restart: always
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - REVERSE_PROXY=true
      - SECRET_KEY=ctfd_secret_key_change_this_in_production
    volumes:
      # CTFd 데이터 보존용 볼륨
      - ./ctfd/data/CTFd/logs:/var/log/CTFd
      - ./ctfd/data/CTFd/uploads:/var/uploads
      - ./ctfd/data/CTFd/config.py:/opt/CTFd/CTFd/config.py:ro
      # 테마나 플러그인 커스터마이징용 (선택사항)
      - ./ctfd/data/CTFd/themes:/opt/CTFd/CTFd/themes/custom
    depends_on:
      - db
      - cache
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ctfd.rule=Host(`ctf.localhost`)"
      - "traefik.http.routers.ctfd.entrypoints=web"
      - "traefik.http.services.ctfd.loadbalancer.server.port=8000"

  # CTFd 데이터베이스
  db:
    image: mariadb:10.4.12
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - ./ctfd/data/mysql:/var/lib/mysql
    networks:
      - ctf-network

  # Redis 캐시
  cache:
    image: redis:4
    restart: always
    volumes:
      - ./ctfd/data/redis:/data
    networks:
      - ctf-network

  # 웹 문제들
  web-ann-day:
    build: ./challenges/ann_day
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ann-day.rule=Host(`ann-day.ctf.localhost`)"
      - "traefik.http.routers.ann-day.entrypoints=web"
      - "traefik.http.services.ann-day.loadbalancer.server.port=5000"

  web-base64:
    build: ./challenges/base64
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.base64.rule=Host(`base64.ctf.localhost`)"
      - "traefik.http.routers.base64.entrypoints=web"
      - "traefik.http.services.base64.loadbalancer.server.port=5000"

  web-calculating-game:
    build: ./challenges/calculating_game
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calculating-game.rule=Host(`calculating-game.ctf.localhost`)"
      - "traefik.http.routers.calculating-game.entrypoints=web"
      - "traefik.http.services.calculating-game.loadbalancer.server.port=80"

  web-cookieadmin:
    build: ./challenges/cookieadmin
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cookieadmin.rule=Host(`cookieadmin.ctf.localhost`)"
      - "traefik.http.routers.cookieadmin.entrypoints=web"
      - "traefik.http.services.cookieadmin.loadbalancer.server.port=5000"

  web-cookie-ctf:
    build: ./challenges/cookie_ctf
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cookie-ctf.rule=Host(`cookie-ctf.ctf.localhost`)"
      - "traefik.http.routers.cookie-ctf.entrypoints=web"
      - "traefik.http.services.cookie-ctf.loadbalancer.server.port=5000"

  web-crypto-hacker:
    build: ./challenges/crypto-hacker
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crypto-hacker.rule=Host(`crypto-hacker.ctf.localhost`)"
      - "traefik.http.routers.crypto-hacker.entrypoints=web"
      - "traefik.http.services.crypto-hacker.loadbalancer.server.port=5000"

  web-directory-trav:
    build: ./challenges/directory_trav
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.directory-trav.rule=Host(`directory-trav.ctf.localhost`)"
      - "traefik.http.routers.directory-trav.entrypoints=web"
      - "traefik.http.services.directory-trav.loadbalancer.server.port=5000"

  web-hidden-images:
    build: ./challenges/hidden_images
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hidden-images.rule=Host(`hidden-images.ctf.localhost`)"
      - "traefik.http.routers.hidden-images.entrypoints=web"
      - "traefik.http.services.hidden-images.loadbalancer.server.port=5000"

  web-mobile-only:
    build: ./challenges/mobile_only
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mobile-only.rule=Host(`mobile-only.ctf.localhost`)"
      - "traefik.http.routers.mobile-only.entrypoints=web"
      - "traefik.http.services.mobile-only.loadbalancer.server.port=5000"

  web-path-ctf:
    build: ./challenges/path_ctf
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.path-ctf.rule=Host(`path-ctf.ctf.localhost`)"
      - "traefik.http.routers.path-ctf.entrypoints=web"
      - "traefik.http.services.path-ctf.loadbalancer.server.port=5000"

  web-regex-ctf:
    build: ./challenges/regex_ctf
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.regex-ctf.rule=Host(`regex-ctf.ctf.localhost`)"
      - "traefik.http.routers.regex-ctf.entrypoints=web"
      - "traefik.http.services.regex-ctf.loadbalancer.server.port=5000"

  web-why-so-many-click:
    build: ./challenges/why_so_many_click
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.why-so-many-click.rule=Host(`why-so-many-click.ctf.localhost`)"
      - "traefik.http.routers.why-so-many-click.entrypoints=web"
      - "traefik.http.services.why-so-many-click.loadbalancer.server.port=5000"

  # DMCP 서비스들
  dmcp:
    build: ./damn-vulnerable-MCP-server
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dmcp-9001.rule=Host(`dmcp-9001.ctf.localhost`)"
      - "traefik.http.routers.dmcp-9001.entrypoints=web"
      - "traefik.http.services.dmcp-9001.loadbalancer.server.port=9001"
      - "traefik.http.routers.dmcp-9002.rule=Host(`dmcp-9002.ctf.localhost`)"
      - "traefik.http.services.dmcp-9002.loadbalancer.server.port=9002"
      - "traefik.http.routers.dmcp-9006.rule=Host(`dmcp-9006.ctf.localhost`)"
      - "traefik.http.services.dmcp-9006.loadbalancer.server.port=9006"
      - "traefik.http.routers.dmcp-9007.rule=Host(`dmcp-9007.ctf.localhost`)"
      - "traefik.http.services.dmcp-9007.loadbalancer.server.port=9007"