version: '3.8'

networks:
  ctf-network:
    driver: bridge

services:
  # Traefik 리버스 프록시
  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Traefik 대시보드
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ctf-network

  # CTFd 플랫폼 (메인 루트)
  ctfd:
    image: ctfd/ctfd:latest
    restart: always
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - REVERSE_PROXY=true
      - SECRET_KEY=ctfd_secret_key_change_this_in_production
    volumes:
      - ./ctfd/data/CTFd/logs:/var/log/CTFd
      - ./ctfd/data/CTFd/uploads:/var/uploads
      - ./ctfd/data/CTFd/config.py:/opt/CTFd/CTFd/config.py:ro
      - ./ctfd/data/CTFd/themes:/opt/CTFd/CTFd/themes/custom
    depends_on:
      - db
      - cache
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ctfd.rule=PathPrefix(`/`)"
      - "traefik.http.routers.ctfd.priority=1"
      - "traefik.http.services.ctfd.loadbalancer.server.port=8000"

  # CTFd 데이터베이스
  db:
    image: mariadb:10.4.12
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - ./ctfd/data/mysql:/var/lib/mysql
    networks:
      - ctf-network

  # Redis 캐시
  cache:
    image: redis:4
    restart: always
    volumes:
      - ./ctfd/data/redis:/data
    networks:
      - ctf-network

  # 웹 문제들 (경로 기반)
  web-ann-day:
    build: ./challenges/ann_day
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ann-day.rule=PathPrefix(`/ann-day`)"
      - "traefik.http.routers.ann-day.priority=10"
      - "traefik.http.middlewares.ann-day-strip.stripprefix.prefixes=/ann-day"
      - "traefik.http.routers.ann-day.middlewares=ann-day-strip"
      - "traefik.http.services.ann-day.loadbalancer.server.port=5000"

  web-base64:
    build: ./challenges/base64
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.base64.rule=PathPrefix(`/base64`)"
      - "traefik.http.routers.base64.priority=10"
      - "traefik.http.middlewares.base64-strip.stripprefix.prefixes=/base64"
      - "traefik.http.routers.base64.middlewares=base64-strip"
      - "traefik.http.services.base64.loadbalancer.server.port=5000"

  web-calculating-game:
    build: ./challenges/calculating_game
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calculating-game.rule=PathPrefix(`/calculating-game`)"
      - "traefik.http.routers.calculating-game.priority=10"
      - "traefik.http.middlewares.calculating-game-strip.stripprefix.prefixes=/calculating-game"
      - "traefik.http.routers.calculating-game.middlewares=calculating-game-strip"
      - "traefik.http.services.calculating-game.loadbalancer.server.port=80"

  web-cookieadmin:
    build: ./challenges/cookieadmin
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cookieadmin.rule=PathPrefix(`/cookieadmin`)"
      - "traefik.http.routers.cookieadmin.priority=10"
      - "traefik.http.middlewares.cookieadmin-strip.stripprefix.prefixes=/cookieadmin"
      - "traefik.http.routers.cookieadmin.middlewares=cookieadmin-strip"
      - "traefik.http.services.cookieadmin.loadbalancer.server.port=5000"

  web-cookie-ctf:
    build: ./challenges/cookie_ctf
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cookie-ctf.rule=PathPrefix(`/cookie-ctf`)"
      - "traefik.http.routers.cookie-ctf.priority=10"
      - "traefik.http.middlewares.cookie-ctf-strip.stripprefix.prefixes=/cookie-ctf"
      - "traefik.http.routers.cookie-ctf.middlewares=cookie-ctf-strip"
      - "traefik.http.services.cookie-ctf.loadbalancer.server.port=5000"

  web-crypto-hacker:
    build: ./challenges/crypto-hacker
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crypto-hacker.rule=PathPrefix(`/crypto-hacker`)"
      - "traefik.http.routers.crypto-hacker.priority=10"
      - "traefik.http.middlewares.crypto-hacker-strip.stripprefix.prefixes=/crypto-hacker"
      - "traefik.http.routers.crypto-hacker.middlewares=crypto-hacker-strip"
      - "traefik.http.services.crypto-hacker.loadbalancer.server.port=5000"

  web-directory-trav:
    build: ./challenges/directory_trav
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.directory-trav.rule=PathPrefix(`/directory-trav`)"
      - "traefik.http.routers.directory-trav.priority=10"
      - "traefik.http.middlewares.directory-trav-strip.stripprefix.prefixes=/directory-trav"
      - "traefik.http.routers.directory-trav.middlewares=directory-trav-strip"
      - "traefik.http.services.directory-trav.loadbalancer.server.port=5000"

  web-hidden-images:
    build: ./challenges/hidden_images
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hidden-images.rule=PathPrefix(`/hidden-images`)"
      - "traefik.http.routers.hidden-images.priority=10"
      - "traefik.http.middlewares.hidden-images-strip.stripprefix.prefixes=/hidden-images"
      - "traefik.http.routers.hidden-images.middlewares=hidden-images-strip"
      - "traefik.http.services.hidden-images.loadbalancer.server.port=5000"

  web-mobile-only:
    build: ./challenges/mobile_only
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mobile-only.rule=PathPrefix(`/mobile-only`)"
      - "traefik.http.routers.mobile-only.priority=10"
      - "traefik.http.middlewares.mobile-only-strip.stripprefix.prefixes=/mobile-only"
      - "traefik.http.routers.mobile-only.middlewares=mobile-only-strip"
      - "traefik.http.services.mobile-only.loadbalancer.server.port=5000"

  web-path-ctf:
    build: ./challenges/path_ctf
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.path-ctf.rule=PathPrefix(`/path-ctf`)"
      - "traefik.http.routers.path-ctf.priority=10"
      - "traefik.http.middlewares.path-ctf-strip.stripprefix.prefixes=/path-ctf"
      - "traefik.http.routers.path-ctf.middlewares=path-ctf-strip"
      - "traefik.http.services.path-ctf.loadbalancer.server.port=5000"

  web-regex-ctf:
    build: ./challenges/regex_ctf
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.regex-ctf.rule=PathPrefix(`/regex-ctf`)"
      - "traefik.http.routers.regex-ctf.priority=10"
      - "traefik.http.middlewares.regex-ctf-strip.stripprefix.prefixes=/regex-ctf"
      - "traefik.http.routers.regex-ctf.middlewares=regex-ctf-strip"
      - "traefik.http.services.regex-ctf.loadbalancer.server.port=5000"

  web-why-so-many-click:
    build: ./challenges/why_so_many_click
    networks:
      - ctf-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.why-so-many-click.rule=PathPrefix(`/why-so-many-click`)"
      - "traefik.http.routers.why-so-many-click.priority=10"
      - "traefik.http.middlewares.why-so-many-click-strip.stripprefix.prefixes=/why-so-many-click"
      - "traefik.http.routers.why-so-many-click.middlewares=why-so-many-click-strip"
      - "traefik.http.services.why-so-many-click.loadbalancer.server.port=5000"

  # DMCP 서비스들
  dmcp-9001:
    build: ./damn-vulnerable-MCP-server
    networks:
      - ctf-network
    environment:
      - SERVICE_NAME=dmcp-9001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dmcp-9001.rule=PathPrefix(`/dmcp-9001`)"
      - "traefik.http.routers.dmcp-9001.priority=10"
      - "traefik.http.middlewares.dmcp-9001-strip.stripprefix.prefixes=/dmcp-9001"
      - "traefik.http.routers.dmcp-9001.middlewares=dmcp-9001-strip"
      - "traefik.http.services.dmcp-9001.loadbalancer.server.port=9001"

  dmcp-9002:
    build: ./damn-vulnerable-MCP-server
    networks:
      - ctf-network
    environment:
      - SERVICE_NAME=dmcp-9002
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dmcp-9002.rule=PathPrefix(`/dmcp-9002`)"
      - "traefik.http.routers.dmcp-9002.priority=10"
      - "traefik.http.middlewares.dmcp-9002-strip.stripprefix.prefixes=/dmcp-9002"
      - "traefik.http.routers.dmcp-9002.middlewares=dmcp-9002-strip"
      - "traefik.http.services.dmcp-9002.loadbalancer.server.port=9002"

  dmcp-9006:
    build: ./damn-vulnerable-MCP-server
    networks:
      - ctf-network
    environment:
      - SERVICE_NAME=dmcp-9006
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dmcp-9006.rule=PathPrefix(`/dmcp-9006`)"
      - "traefik.http.routers.dmcp-9006.priority=10"
      - "traefik.http.middlewares.dmcp-9006-strip.stripprefix.prefixes=/dmcp-9006"
      - "traefik.http.routers.dmcp-9006.middlewares=dmcp-9006-strip"
      - "traefik.http.services.dmcp-9006.loadbalancer.server.port=9006"

  dmcp-9007:
    build: ./damn-vulnerable-MCP-server
    networks:
      - ctf-network
    environment:
      - SERVICE_NAME=dmcp-9007
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dmcp-9007.rule=PathPrefix(`/dmcp-9007`)"
      - "traefik.http.routers.dmcp-9007.priority=10"
      - "traefik.http.middlewares.dmcp-9007-strip.stripprefix.prefixes=/dmcp-9007"
      - "traefik.http.routers.dmcp-9007.middlewares=dmcp-9007-strip"
      - "traefik.http.services.dmcp-9007.loadbalancer.server.port=9007"