#!/bin/bash

DOMAIN="${1:-ctf.localhost}"
PROTOCOL="${2:-http}"

echo "🔗 CTF 문제 URL 목록 (CTFd 설정용)"
echo "=================================="
echo ""
echo "메인 플랫폼: ${PROTOCOL}://${DOMAIN}"
echo ""
echo "웹 문제들:"
echo "ann_day: ${PROTOCOL}://ann-day.${DOMAIN}"
echo "base64: ${PROTOCOL}://base64.${DOMAIN}"
echo "calculating_game: ${PROTOCOL}://calculating-game.${DOMAIN}"
echo "cookieadmin: ${PROTOCOL}://cookieadmin.${DOMAIN}"
echo "cookie_ctf: ${PROTOCOL}://cookie-ctf.${DOMAIN}"
echo "crypto_hacker: ${PROTOCOL}://crypto-hacker.${DOMAIN}"
echo "directory_trav: ${PROTOCOL}://directory-trav.${DOMAIN}"
echo "hidden_images: ${PROTOCOL}://hidden-images.${DOMAIN}"
echo "mobile_only: ${PROTOCOL}://mobile-only.${DOMAIN}"
echo "path_ctf: ${PROTOCOL}://path-ctf.${DOMAIN}"
echo "regex_ctf: ${PROTOCOL}://regex-ctf.${DOMAIN}"
echo "why_so_many_click: ${PROTOCOL}://why-so-many-click.${DOMAIN}"
echo ""
echo "DMCP 서비스들:"
echo "dmcp-9001: ${PROTOCOL}://dmcp-9001.${DOMAIN}"
echo "dmcp-9002: ${PROTOCOL}://dmcp-9002.${DOMAIN}"
echo "dmcp-9006: ${PROTOCOL}://dmcp-9006.${DOMAIN}"
echo "dmcp-9007: ${PROTOCOL}://dmcp-9007.${DOMAIN}"
echo ""
echo "💡 /etc/hosts에 추가할 내용:"
echo "127.0.0.1 ${DOMAIN} ann-day.${DOMAIN} base64.${DOMAIN} calculating-game.${DOMAIN} cookieadmin.${DOMAIN} cookie-ctf.${DOMAIN} crypto-hacker.${DOMAIN} directory-trav.${DOMAIN} hidden-images.${DOMAIN} mobile-only.${DOMAIN} path-ctf.${DOMAIN} regex-ctf.${DOMAIN} why-so-many-click.${DOMAIN} dmcp-9001.${DOMAIN} dmcp-9002.${DOMAIN} dmcp-9006.${DOMAIN} dmcp-9007.${DOMAIN}"