#!/bin/bash

DOMAIN="${1:-49.50.135.227}"
PROTOCOL="${2:-http}"

echo "🔗 CTF 경로 기반 URL 목록 (CTFd 설정용)"
echo "=================================="
echo ""
echo "메인 CTFd 플랫폼: ${PROTOCOL}://${DOMAIN}/"
echo ""
echo "웹 문제들:"
echo "ann_day: ${PROTOCOL}://${DOMAIN}/ann-day"
echo "base64: ${PROTOCOL}://${DOMAIN}/base64"
echo "calculating_game: ${PROTOCOL}://${DOMAIN}/calculating-game"
echo "cookieadmin: ${PROTOCOL}://${DOMAIN}/cookieadmin"
echo "cookie_ctf: ${PROTOCOL}://${DOMAIN}/cookie-ctf"
echo "crypto_hacker: ${PROTOCOL}://${DOMAIN}/crypto-hacker"
echo "directory_trav: ${PROTOCOL}://${DOMAIN}/directory-trav"
echo "hidden_images: ${PROTOCOL}://${DOMAIN}/hidden-images"
echo "mobile_only: ${PROTOCOL}://${DOMAIN}/mobile-only"
echo "path_ctf: ${PROTOCOL}://${DOMAIN}/path-ctf"
echo "regex_ctf: ${PROTOCOL}://${DOMAIN}/regex-ctf"
echo "why_so_many_click: ${PROTOCOL}://${DOMAIN}/why-so-many-click"
echo ""
echo "DMCP 서비스들:"
echo "dmcp-9001: ${PROTOCOL}://${DOMAIN}/dmcp-9001"
echo "dmcp-9002: ${PROTOCOL}://${DOMAIN}/dmcp-9002"
echo "dmcp-9006: ${PROTOCOL}://${DOMAIN}/dmcp-9006"
echo "dmcp-9007: ${PROTOCOL}://${DOMAIN}/dmcp-9007"
echo ""
echo "🎯 사용자들이 접속할 수 있는 URL들:"
echo "=================================="
echo "CTFd 메인: ${PROTOCOL}://${DOMAIN}/"
echo "ann_day 문제: ${PROTOCOL}://${DOMAIN}/ann-day"
echo "base64 문제: ${PROTOCOL}://${DOMAIN}/base64"
echo "calculating_game 문제: ${PROTOCOL}://${DOMAIN}/calculating-game"
echo "기타 문제들: ${PROTOCOL}://${DOMAIN}/[문제이름]"